server:
  port: 9000

spring:
  application:
    name: "cards"
  profiles:
    active: qa
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # Add this line to specify the MySQL driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  config:
    import: optional:configserver:http://localhost:8071/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  health:
    probes:
      enabled: true
    refresh:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Bank cards application"
    version: "1.0.0"
